vector.mml check ignores inner rings.
If there are two inner rings intersecting in a point, then ST_ApproximateMedialAxis() raises error:

  psycopg2.InternalError: straight skeleton of Polygon with touching interior rings is not implemented

As mml check is focused on linear structures, inner rings are irrelevant.
Therefore, the new implementation works on outer ring only.